title: My blog
author: GitHub User
email: kepes.miklos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Description goes here
# social links
#twitter_username: your-twitter-handle
github_username:  mekhlos

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima